# Site title
title: "SyRF User Guide"

# Jekyll theme
remote_theme: just-the-docs/just-the-docs

# Search functionality (true / false)
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Go to SyRF":
    - "https://syrf.org.uk/"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International (CC BY 4.0) License</a>."
