version: '2'
services:
  site:
    environment:
      - JEKYLL_ENV=docker
      - BUNDLE_GEMFILE=Gemfile.dev
    command: jekyll serve --config  _config.dev.yml,_config.docker.yml  -l --livereload-port 4050 --force_polling
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 4050:4050